### ISSUE TITLE
Can't override imported descendant components

### ISSUE THREAD

**Issue by souporserious** [wooorm/xdm#104]
---

Hello, not sure if I'm doing something wrong, but I can't seem to override imported components when using the esbuild plugin. I first tried the [components prop](https://github.com/wooorm/xdm#mdx-content) and then setting up `@mdx-js/react` and using `MDXProvider`, but neither seem to work for imported MDX files.

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: 3.3.1

### Steps to reproduce

Use the esbuild plugin to compile multiple MDX files ([source](https://github.com/souporserious/documenting-systems-in-nextjs/blob/xdm-components/data/get-component-readme.ts#L36-L44)):

```ts
const result = await esbuild.build({
  entryPoints: [componentReadmePath],
  target: 'esnext',
  format: 'esm',
  bundle: true,
  write: false,
  plugins: [xdm(xdmOptions)],
  external: ['react', 'react-dom'],
})
```

Try overriding any component in [imported MDX files](https://github.com/souporserious/documenting-systems-in-nextjs/tree/xdm-components/components/Box) ([source](https://github.com/souporserious/documenting-systems-in-nextjs/blob/xdm-components/pages/components/%5Bcomponent%5D/index.tsx#L17-L22)):

```tsx
<Readme
  components={{
    h2: () => <div>Override</div>,
    h3: () => <div>Override</div>,
  }}
/>
```

Link to branch with code example: 
[Example](https://github.com/souporserious/documenting-systems-in-nextjs/tree/xdm-components)

To run the demo locally:

```bash
yarn && yarn dev
```

To see an example visit:
http://localhost:4000/components/box

The `h2` is correctly overridden, but the `h3` from the imported file is not.

### Expected behavior

The descendant components in the imported MDX file should be overridden.

### Actual behavior

Only the main file is overridden and imported files are not.

**Comment by wooorm** [comment]
- I get an error when trying to first run `yarn dev`, that `'.data'` can’t be imported
- When passing components (`<Readme components={...}>`), the provider isn’t needed
- When opening `http://localhost:4000/components/box`, I see the word `Override` in the `<h2>, which indicates that it works fine?

**Comment by souporserious** [comment]
Oops, sorry about that! I changed the build around recently and think I borked fresh installs. I figured I was doing something wrong 🤦‍♂️ makes sense that it was adding different providers since esbuild included its own version. Thank you for taking a look, everything is working great now, I appreciate the help! 🙏
