### ISSUE TITLE
How to get tree from compile ?

### ISSUE THREAD

**Issue by dmitryshelomanov** [wooorm/xdm#107]
I need compile's tree and render it  in react
I want to try crate editor with tree from server api
(I need light weight render without evulate and etc)

**Comment by wooorm** [comment]
Impossible

**Comment by dmitryshelomanov** [comment]
@wooorm 

why ? I have tree and can traverse it

```js
traverse(tree, components)
```

I thought such libraries already exist

**Comment by wooorm** [comment]
Yes, you can do such things. Your question is vague. This project doesn’t do that. This project compiles MDX -> JS.
