### ISSUE TITLE
Add `format` option, defaulting to `'mdx'`, optionally `'detect'` to treat `.md` as plain markdown

### ISSUE THREAD

**Issue by wooorm** [wooorm/xdm#17]
Problem:

- Given MDX is moving a bit further from markdown:
  ```markdown
  <div>
    *this was not emphasis before, in alignment with markdown, but now it is*
  </div>
  ```
- And given that folks will also have plain markdown,
- And finally given that xdm comes with a lot of nice tooling for using MD(X) in esbuild/rollup/webpack/snowpack/vite/RSC/etc,
- Therefore it seems like a good addition to support plain markdown by not adding `remark-mdx`, in a flag.

Solution:

* The `detect` value would detect mdx or md based on a file extension
* `mdx` / `md` would toggle `remark-mdx` on or off
* To not break current usage, the default will be `mdx`, if that doesn’t matter, the default could be `detect`
* Folks can pass `rehype-raw` if they want the HTML in their markdown to “work”. If they didn’t set it, we’d strip it out. Include `rehype-raw` would be pretty big, so I’d prefer not importing it by default.
* We’d need to turn on `allowDangerousHtml` for `remark-rehype`, which can always be there, given that we’re either not getting it (if remark-mdx is there), or compiling it away (if `rehype-raw` is there), or filtering any remaining html nodes out

**Comment by remcohaszing** [comment]
I’m using plain markdown files exclusively (yet). However, I do use features in my transforms, for example [here](https://gitlab.com/appsemble/appsemble/-/blob/master/packages/webpack-core/src/remark/images.ts). (This still uses `@mdx-js/mdx`, but my `xdm` merge request is green and will be merged soon.)

The main issue I’m still running into, is that HTML comments aren’t supported in MDX. I think a good solution would be to distinguish between remark plugins and MDX plugins.

https://github.com/wooorm/xdm/blob/e87ab66115bff526b9ccae79081e5b807607017d/lib/core.js#L76-L80

```diff
    unified()
      .use(remarkParse)
+     .use(remarkPlugins)
      .use(remarkMdx)
+     .use(mdxPlugins)
-     .use(remarkPlugins)
      .use(remarkRehype, {
```

This way remark plugins can just work with MDAST and don’t have to take MDX specifics into account, whilst MDX plugins are explicitly written to work with MDXAST. I.e. [remark-remove-comments](https://www.npmjs.com/package/remark-remove-comments) could strip HTML comments from the MDAST the AST is passed to `remarkMdx`.

**Comment by wooorm** [comment]
> However, I do use features in my transforms.

That should work! The rest of the pipeline can handle the esm and jsx nodes that plugins add!

So I think you could switch to use `'md'`, use your plugins to generate esm and jsx nodes, and we’ll strip HTML out anyway (unless you’re passing rehype-raw in)

**Comment by remcohaszing** [comment]
> That should work! The rest of the pipeline can handle the esm and jsx nodes that plugins add!

In that case, never mind my _remarks_ :smile:
