### ISSUE TITLE
Unexpected `p` in jsx output

### ISSUE THREAD

**Issue by chenxsan** [wooorm/xdm#20]
Here's the code to run in Node REPL once you have `xdm` installed:

```js
import('xdm').then(({compileSync}) => console.log(compileSync(`<div>
Author:
<a rel="author" href="https://github.com/">
  Sam
</a>
</div>
`)))
```

Here's the result:

```bash
VFile {
  data: {},
  messages: [],
  history: [],
  cwd: '/Users/sam/Documents/githubRepos/xdm-test',
  contents: '/*@jsxRuntime automatic @jsxImportSource react*/\n' +
    'import {Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs} from "react/jsx-runtime";\n' +
    'function MDXContent(_props) {\n' +
    '  const _components = Object.assign({\n' +
    '    p: "p"\n' +
    '  }, _props.components), {wrapper: MDXLayout} = _components;\n' +
    '  const _content = _jsx(_Fragment, {\n' +
    '    children: _jsxs("div", {\n' +
    '      children: [_jsx(_components.p, {\n' +
    '        children: "Author:"\n' +
    '      }), _jsx("a", {\n' +
    '        rel: "author",\n' +
    '        href: "https://github.com/",\n' +
    '        children: _jsx(_components.p, {\n' +
    '          children: "Sam"\n' +
    '        })\n' +
    '      })]\n' +
    '    })\n' +
    '  });\n' +
    '  return MDXLayout ? _jsx(MDXLayout, Object.assign({}, _props, {\n' +
    '    children: _content\n' +
    '  })) : _content;\n' +
    '}\n' +
    'export default MDXContent;\n'
}
```
As you can see in the result, there's a `p` around `Author` text, which I believe is wrong considering those are JSX syntax.

And here's the result of [mdxjs playground](https://mdxjs.com/playground) :

```js
/* @jsxRuntime classic */
/* @jsx mdx */
const layoutProps = {
  
};
const MDXLayout = "wrapper"
function MDXContent({
  components,
  ...props
}) {
  return <MDXLayout {...layoutProps} {...props} components={components} mdxType="MDXLayout">
    <div>
  Author:
  <a rel="author" href="https://github.com/">
    Sam
  </a>
    </div>
    </MDXLayout>;
}
;
MDXContent.isMDXComponent = true;
```

**Comment by wooorm** [comment]
I think the current output makes the most sense. Formatted a bit differently, maybe more so:

```jsx
<div>
Author: <a rel="author" href="https://github.com/">Sam</a>
</div>
```

The reason is that I also expect links, emphasis and such to work there:

```jsx
<div>
Author: [Sam](https://github.com/)
</div>
```

---

Other than being unexpected, is the paragraph an *actual* problem?

**Comment by chenxsan** [comment]
Let me use a minimal example to show my concern.

Here's a jsx code:

```jsx
<>
  <div>
    Author
  </div>
  <div>Author</div>
</>
```
And here's output of [babel playground](https://babeljs.io/repl#?browsers=defaults%2C%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DwPgUABBwCYJYDdxSgQQK4BcAWB7ATpNAPTxJGyIgY4HClVj0hA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cstage-2&prettier=false&targets=&version=7.13.9&externalPlugins=):

```js
import { jsx as _jsx } from "react/jsx-runtime";
import { Fragment as _Fragment } from "react/jsx-runtime";
import { jsxs as _jsxs } from "react/jsx-runtime";

/*#__PURE__*/
_jsxs(_Fragment, {
  children: [/*#__PURE__*/_jsx("div", {
    children: "Author"
  }), /*#__PURE__*/_jsx("div", {
    children: "Author"
  })]
});
```
As you can see, formatting doesn't really matter in JSX.

But it does matter in xdm, here's the output of the aforementioned jsx code:

```js
'/*@jsxRuntime automatic @jsxImportSource react*/\n' +
    'import {Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs} from "react/jsx-runtime";\n' +
    'function MDXContent(_props) {\n' +
    '  const _components = Object.assign({\n' +
    '    p: "p"\n' +
    '  }, _props.components), {wrapper: MDXLayout} = _components;\n' +
    '  const _content = _jsx(_Fragment, {\n' +
    '    children: _jsxs(_Fragment, {\n' +
    '      children: [_jsx("div", {\n' +
    '        children: _jsx(_components.p, {\n' +
    '          children: "Author"\n' +
    '        })\n' +
    '      }), _jsx("div", {\n' +
    '        children: "Author"\n' +
    '      })]\n' +
    '    })\n' +
    '  });\n' +
    '  return MDXLayout ? _jsx(MDXLayout, Object.assign({}, _props, {\n' +
    '    children: _content\n' +
    '  })) : _content;\n' +
    '}\n' +
    'export default MDXContent;\n'
```
Which means when formatting tools like prettier enabled, xdm is going to have a problem.

BTW, I myself have never used any markdown syntax inside HTML as I think it's better to have a clear boundary between them.

**Comment by wooorm** [comment]
> BTW, I myself have never used any markdown syntax inside HTML as I think it's better to have a clear boundary between them.

We got a lot of feedback on MDX 0 and MDX 1 that folks *really wanted* markdown in their tags. CM has a pretty clear boundary:

```
<div>

  *works*

</div>

<div>
  *does not work*
</div>
```

But folks were very vocal that they expected both to work, so that was changed.

---

> Which means when formatting tools like prettier enabled, xdm is going to have a problem.

Prettier will still have to update for the changes in the MDX format.

**Comment by chenxsan** [comment]
Thank you, I've checked the commonmark spec https://spec.commonmark.org/0.29/#example-136, indeed, it's valid to use markdown inside html, so it makes sense when people want to use markdown inside JSX.

And I just noticed this issue https://github.com/prettier/prettier/issues/7041 on prettier.

Anyway, since we're writing JSX in markdown, it makes sense to comply with the markdown spec, which means formatting matters even for JSX although it's not true in other use cases.

**Comment by wooorm** [comment]
:+1:

I appreciate hearing these problems btw; I’m mostly coming from the “compiler” side, and trying to make that make sense. So I might miss what makes sense to users.

MDX is an interesting mix between JSX and Markdown. Not quite either. Something in between.
