### ISSUE TITLE
Outputs contains conflicting const declarations if plugins use _components

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/xdm#21]
In `remark-mdx-images` I the following [input](https://raw.githubusercontent.com/remcohaszing/remark-mdx-images/main/__fixtures__/alt/input.md) yields the following [output](https://github.com/remcohaszing/remark-mdx-images/blob/main/__fixtures__/alt/expected.jsx)

**input**

```md
![Alt text](image.png)
```

**output**

```jsx
/*@jsxRuntime automatic @jsxImportSource react*/
import __0___image_png__ from "./image.png";
function MDXContent(_props) {
  const _components = Object.assign({
    p: "p"
  }, _props.components), {wrapper: MDXLayout, _components} = _components;
  const _content = <><_components.p><_components.img alt="Alt text" src={__0___image_png__} /></_components.p></>;
  return MDXLayout ? <MDXLayout {..._props}>{_content}</MDXLayout> : _content;
}
export default MDXContent;
```

In other words: `_components` is declared twice if a remark mdx plugin yields usage of `_components`. This also occurs when the `jsx` option or `providerImportSource` is set.

I’m using `_components`, because you recommended me to do so in a chat. I’m not a great fan about this, because `_components` feels like it should be an internal API. I think it makes sense if remark plugins could do something like this:

```js
function remarkMdxFoo() {
  this.data('mdxComponentsIdentifier') // Returns '_components'
}
```

**Comment by remcohaszing** [comment]
The difference between `mdxJsxTextElement` and `mdxJsxFlowElement` is that using `mdxJsxFlowElement` will cause the image to be wrapped inside a `<p>` tag, whereas the `mdxJsxTextElement` does not. I think best behavour would be to use the same output as xdm uses, but that differs based on context.

Anyway, `xdm@main` seems seems to wotk the issues regarding the `_components` variable.

As for documenting the `components` prop still works when using `remark-mdx-images`: I’ll add that in the next patch release. :+1:

**Comment by wooorm** [comment]
Released!

> I think best behavour would be to use the same output as xdm uses, but that differs based on context.

I agree! This new patch might change that behavior too, so might be good to re-check whether it still matches
