### ISSUE TITLE
How to use a default wrapper component with the webpack loader

### ISSUE THREAD

**Issue by kripod** [wooorm/xdm#29]
While it’s possible to pass custom components [to content imported from MDX files](https://github.com/wooorm/xdm#mdx-content), I would like to know how to specify a default `wrapper` component in `next.config.js`, as an option given to the webpack plugin.

Thanks in advance for helping me out!

**Comment by wooorm** [comment]
You can’t. Layout, like other components, has to do with the runtime.
A next or webpack config is at a whole nother level

This might be an XY problem: https://xyproblem.info.
