### ISSUE TITLE
Regarding `inlineCode` under `xdm` and `@mdx-js/loader`

### ISSUE THREAD

**Issue by chenxsan** [wooorm/xdm#3]
I'm replacing `@mdx-js/loader` with `xdm` in my project https://github.com/chenxsan/voidjs/pull/426/files#diff-a94978bc24b042c57f0140409ac8c8101cad618fd24c90a2d88136e193b92e14, everything works fine (that's impressive!) but one.

With `@mdx-js/loader`, I can customize [`inlineCode`](https://mdxjs.com/table-of-components#table-of-components) targeting inline code like below:

```js
// `this is inline code` I want to target
const inlineCode = (props) => <code className="bg-gray-200 px-2" {...props} />
<MDXProvider components={{inlineCode}>
  // ...
</MDXProvider>
```

![image](https://user-images.githubusercontent.com/1091472/107512874-65d26400-6be2-11eb-91ff-da5943da4a82.png)

However with `xdm`, inline code seem to be handled by `code`:

```js
// `this is inline code` I want to target
const code = (props) => <code className="bg-gray-200 px-2" {...props} />
<MDXProvider components={{code}>
  // ...
</MDXProvider>
```
![image](https://user-images.githubusercontent.com/1091472/107512525-ee043980-6be1-11eb-9b1b-6927d9c19a8b.png)

But I didn't find anything related to this change in the doc.

**Comment by wooorm** [comment]
Ah correct, I removed that too, I’ll add it to the notes on the differences below.

Are you also asking about help with differentiating between “inline” and “block” code? If so: this might help: for blocks you can sometimes use `pre`, or otherwise check if there’s a `language-\w+` `className`

**Comment by wooorm** [comment]
Also very cool to hear that switching was mostly fine! Do let me know if there is anything missing or complex!

**Comment by chenxsan** [comment]
> Ah correct, I removed that too, I’ll add it to the notes on the differences below.
> 
> Are you also asking about help with differentiating between “inline” and “block” code? If so: this might help: for blocks you can sometimes use `pre`, or otherwise check if there’s a `language-\w+` `className`

Thanks for your help!

**Comment by aFcFzF** [comment]
> 

sorry，I’m  confuse about，blockCode render <pre><code>111</code></pre> also call inlineCode<code><code>, It seem nest mixed. check props.children.props.className seem not graceful。

![image](https://user-images.githubusercontent.com/19820728/153981679-93d67ca4-a3b3-4407-a476-b710b7c98743.png)

![image](https://user-images.githubusercontent.com/19820728/153981660-85f8eb8a-4b61-4cd3-89b0-a7dbb6656cbd.png)
