### ISSUE TITLE
Support for codeblock meta string?

### ISSUE THREAD

**Issue by MaximeHeckel** [wooorm/xdm#31]
Hi 👋 

I started testing out xdm on my MDX based blog and so far I love it. I come from `mdx-js` and I found out that `xdm` does not parse code blocks `pre` the same way as `mdx-js` does.

For example I'd often define arbitrary key/values after specifying the language for my codeblock

```
```js title=foo

// Code block
```

or even some arbitrary syntax to highlight specific lines

```
```js {1-2}
// Code block
```

and I was always able to get back those values as props on the React side of things. 

(Another example from the mdx-js docs: https://mdxjs.com/guides/live-code passing `live=true` to render an alternative codeblock component) 

However, I don't seem to be able to get the same behavior with `xdm`. Do you have any tips or workaround for this? Or is this simply not supported?

Thank you in advance!

**Comment by wooorm** [comment]
Did you see the guide in the readme? https://github.com/wooorm/xdm#syntax-highlighting

**Comment by MaximeHeckel** [comment]
I guess I skipped the highlighting part figuring out it was simply about "color highlighting" 😄 
Thank you and sorry for the noise!

**Comment by wooorm** [comment]
fwiw, if you’d want to package that code up as `rehype-mdx-meta` or so, I’ll link to it in that section (+ https://github.com/wooorm/xdm#plugins)
