### ISSUE TITLE
`iframe` crashes

### ISSUE THREAD

**Issue by IanMitchell** [wooorm/xdm#38]
First of all, this might not be the right repo for this error report - apologies if I've gotten it wrong, there's a lot of stuff going in in the code 😅 

I'm running mdx-bundler on Next.js, and I'm getting crashes when I have embedded Codepen iframes in my MDX files. I think it has to do with how Codepen has text within the iframe - they look something like this:

```html
<iframe
  height="265"
  scrolling="no"
  title="Extend Background Color"
  src="//codepen.io/IanMitchell/embed/BJRzML/?height=265&theme-id=0&default-tab=css,result&embed-version=2"
  frameBorder="no"
  allowtransparency="true"
  allowFullScreen={true}
  width="100%"
>
  See the Pen{" "}
  <a href="https://codepen.io/IanMitchell/pen/BJRzML/">
    Extend Background Color
  </a>{" "}
  by Ian Mitchell (<a href="https://codepen.io/IanMitchell">@IanMitchell</a>) on{" "}
  <a href="https://codepen.io">CodePen</a>.
</iframe>
```

If I remove all of the inner content of the `iframe` and make it a self-closing tag, things work perfectly. When there is content between the tags though, I get the following error:

```
node_modules/mdast-util-from-markdown/dist/index.js:419:12: error: [inMemory] Cannot close `paragraph` (22:3-22:20): a different token (`mdxJsxTextTag`, 22:17-22:20) is open
```

**Comment by wooorm** [comment]
The problem you are running into is that we need to differentiate between blocks and inline, similar to how markdown parses code:

````markdown
```js
this is block level code
```

```this is inline code```
````

Yields:

```js
this is block level code
```

```this is inline code```

---

To differentiate, we look for whether tags are on their own line:

```jsx
<a href="https://codepen.io/IanMitchell/pen/BJRzML/">
```

^-- that looks like a block!

But when we see `</a>{" "}`, that can’t be a block, so there’s a mismatch!

To fix that, place text together with tags:

```jsx
<a href="https://codepen.io/IanMitchell/pen/BJRzML/">Extend Background Color</a>
```

---

Note also that you’re in markdown between tags, no need for `{" "}` hacks!:

```jsx
<iframe {...props}>
  See the Pen
  <a href="https://codepen.io/IanMitchell/pen/BJRzML/">Extend Background Color</a>
  by Ian Mitchell (<a href="https://codepen.io/IanMitchell">@IanMitchell</a>) on
  <a href="https://codepen.io">CodePen</a>.
</iframe>
```

And, you don’t need to use tags at all:

```jsx
<iframe {...props}>
  See the Pen
  [Extend Background Color](https://codepen.io/IanMitchell/pen/BJRzML/)
  by IanMitchell ([@IanMitchell](https://codepen.io/IanMitchell)) on
  [CodePen](https://codepen.io).
</iframe>
```

**Comment by IanMitchell** [comment]
I'm little confused, sorry - my understanding of Markdown is that since there's no extra linebreaks between the tag and content, the entire block should be treated as HTML and not as parsed as Markdown. This for instance would be markdown:

```markdown
<iframe {...props}>

See the Pen [Extend Background Color](https://codepen.io/IanMitchell/pen/BJRzML) by Ian Mitchell ([@IanMitchell](https://codepen.io/IanMitchell))

</iframe>
```

But this would be HTML and remain unparsed:

```html
<iframe {...props}>
See the Pen [Extend Background Color](https://codepen.io/IanMitchell/pen/BJRzML) by Ian Mitchell ([@IanMitchell](https://codepen.io/IanMitchell))
</iframe>
```

Would this just be a difference between markdown and mdx? ([Commonmark ref](https://spec.commonmark.org/0.29/#example-120))

**Comment by wooorm** [comment]
You are correct, that's how it works in markdown!

But there were a lot of issues about how react developers don't expect that behavior, and requested to remove that blank line requirement, to immediately "enter" markdown again after a tag.

That does mean a different rule to differentiate is needed though. A tag on its own line seems most straight forward to me, but I'd love to hear other ideas!

**Comment by IanMitchell** [comment]
Makes sense! I'm well out of my depth here so I doubt I'll be able to come up with an idea you haven't already considered, but if I think of something I'll let you know! 😄 thanks for the replies!

**Comment by IanMitchell** [comment]
Looking for a little bit of direction if you don't mind - I'm thinking of writing a plugin to only apply transformations for the double newlines, but have very little experience in the area and with ASTs. Would a remark plugin be able to accomplish this? Don't want to dive into docs for a few hours or days just to find out it isn't possible 😅 . I thought that an outside plugin might be an elegant way of accomplishing this though - have the default be people expect, and something sticklers like my users and I can easily include.

**Comment by wooorm** [comment]
> to find out it isn't possible

It’s not possible on the AST level: what this is about comes before ASTs.

It would be the responsibility of [`micromark/micromark-extension-mdx-jsx`](https://github.com/micromark/micromark-extension-mdx-jsx) (tokenizer). However, I don’t see it working there either.
The behavior that markdown and `mdx-js/mdx@1` follow, is to search for things that “look like HTML”: strings that looks like tags but might be broken, and passing that through untouched.
We’re now actually parsing those things. Everything is available in the syntax tree. Which allows all those plugins to do their thing (see [Architecture in readme](https://github.com/wooorm/xdm#architecture)).

---

> sticklers like my users and I can easily include.

Can you expand on the difficulties your users and you are experiencing?

**Comment by IanMitchell** [comment]
Heh, glad I checked - thank you! For difficulties, I'm running into problems with content creators who initially write their docs in markdown using a variety of third party applications, and then pull in and include a small subset of MDX enhancements before publishing. Since the text editors use double line breaks in their draft previews to separate HTML and Markdown, it's what they tend to use - they can visualize it "working".

I think this is pretty squarely a me problem though! I had been hoping I could maybe write a plugin to get around it, but it makes sense why it wouldn't work. Again, really appreciate the walkthrough there - thanks!

**Comment by wooorm** [comment]
Some more ideas:

a) For plain markdown as input, pass [`format: 'md'`](https://github.com/wooorm/xdm#optionsformat)

b) If you want (users) to copy/paste raw JSX into MDX, you might consider using braces:

```
This is MDX

{
  // This is JS(X)
}
```

c) If your editors aren’t React developers, you might also consider using `format: md` with [directives](https://github.com/remarkjs/remark-directive). It’s not the prettiest syntax but I’ve found it easier for editors to reason about. Then you *could* use a remark plugin to turn the AST structure of the directives into [MDX JSX nodes](https://github.com/syntax-tree/mdast-util-mdx-jsx#syntax-tree).

**Comment by IanMitchell** [comment]
I'll take a look at those! Thanks for the ideas 😄
