### ISSUE TITLE
How to force xdm to support HTML comments?

### ISSUE THREAD

**Issue by thecodingwizard** [wooorm/xdm#44]
Is there any way to manually configure (or add a plugin to) XDM to support HTML comments `<!-- ... -->` in addition / instead of JSX comments `{/* ... */}`? Some tools like prettier still don't work with JSX comments.

I tried adding a remark plugin but it seems like XDM crashes before that step. Using regex to remove HTML comments prior to the compilation step somewhat screws up line numbering (though I think it's workable if you add empty lines to replace the deleted lines).

**Comment by wooorm** [comment]
Not really. I’m pretty against it.

Are you adding HTML comments in the source? In that case, you should be able to map HTML to JSX comments?

**Comment by thecodingwizard** [comment]
> Are you adding HTML comments in the source? 

Yes.

> In that case, you should be able to map HTML to JSX comments and keep line info correct?

Do you mean replace `<!--` with `{/* ` and `-->` with `*/}`? This seems smart 😅Thanks!
