### ISSUE TITLE
rollup giving error

### ISSUE THREAD

**Issue by vestineo** [wooorm/xdm#46]
Rollupjs is giving error whenever i import 'xdm/rollup.js' 
[!] Error: While loading the Rollup configuration from "rollup.config.js", Node tried to require an ES module from a CommonJS file, which is not supported. A common cause is if there is a package.json file with "type": "module" in the same folder. You can try to fix this by changing the extension of your configuration file to ".cjs" or ".mjs" depending on the content, which will prevent Rollup from trying to preprocess the file but rather hand it to Node directly.

**Comment by wooorm** [comment]
Hi there!

xdm is [ESM only](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). See also https://github.com/wooorm/xdm/issues/40#issuecomment-819268626.
