### ISSUE TITLE
Local components are overridden with erronous ones

### ISSUE THREAD

**Issue by remcohaszing** [wooorm/xdm#53]
The following MDX code

```jsx
export function Foo({ Div = 'div' }) {
  return <Div />;
}
```

Yields:

```jsx
function _missingComponent(name) {
  return function () {
    throw new Error(
      "Component `" + name + "` was not imported, exported, or given"
    );
  };
}

export function Foo({ Div = "div" }) {
  const _components = {
      Div: _missingComponent("Div"),
    },
    { Div } = _components;
  return <Div />;
}
```

This also happens for components defined in the function body, i,e.:

```jsx
export function Foo() {
  const Div = props.Div
  return <Div />;
}
```

I have my doubts if undefined components should be handled by xdm at all. If it’s unhandled, the user would get the runtime error `Uncaught ReferenceError: Div is not defined`, which is a familiar error we all know and ~~love~~ hate.

**Comment by wooorm** [comment]
yeah, I think you’re right.

**Comment by remcohaszing** [comment]
That was fast!

**Comment by adrfoong** [comment]
Not sure if this is the same issue, but feels similar.

With
```jsx
export const Test = () => {
  const Comp = () => <div>hello</div>;
  return (
    <div>
      <Comp />
    </div>
  );
};
```

I get:
```js
export const Test = () => {
  const _components = {
    div: "div"
  }, {Comp} = _components;
  const Comp = () => _jsx(_components.div, {
    children: "hello"
  });
  return _jsx(_components.div, {
    children: _jsx(Comp, {})
  });
};
```

Notice that `Comp` appears twice, which results in a runtime error.

**Comment by wooorm** [comment]
Yep, I think so too. I think exported components should not get components injected into them

**Comment by adrfoong** [comment]
@wooorm Do you mean that I shouldn't create `Comp` in `Test`, or that the result shouldn't inject `Comp` into the output?

**Comment by adrfoong** [comment]
@wooorm Do you mean that I shouldn't create `Comp` in `Test`, or that the result shouldn't inject `Comp` into the output?

**Comment by remcohaszing** [comment]
It means your code should work. It’s a bug in xdm.

I suggest to define `Comp` in a separate file and import it in the mdx file.

**Comment by adrfoong** [comment]
I needed to clarify just in case 😅. Unfortunately in my case I'd have to create the component external to the MDX file and then import it (I'm using mdx-bundler), because I'm using a third party react hook that returns a component. Not ideal, but definitely a workaround.

**Comment by wooorm** [comment]
Fixed & released!
