### ISSUE TITLE
rehype-katex options

### ISSUE THREAD

**Issue by gr-qft** [wooorm/xdm#59]
Hi, thanks for this awesome project. I have a question: according to rehype-katex doc, katex options could be passed along. However, I’m not seeing how I could pass katex options (e.g. macro definitions) when specifying rehype-katex as a rehype plugin. 

Thanks!

**Comment by wooorm** [comment]
Hi there!
The examples on how to pass (remark and) rehype show this: https://github.com/wooorm/xdm#optionsrehypeplugins

**Comment by gr-qft** [comment]
Oh great, thank you!
