### ISSUE TITLE
Warning: source-map provides its own type definitions, so you don't need @types/source-map installed

### ISSUE THREAD

**Issue by deadcoder0904** [wooorm/xdm#60]
`@types/source-map` can be removed as it looks like `source-map` bundles its own types now:

https://github.com/wooorm/xdm/blob/3f121ec2c4280832f4a9010e76622be60d015ba0/package.json#L42

I got a warning while installing `mdx-bundler` so I found out `xdm` uses it:

> npm WARN deprecated @types/source-map@0.5.7: This is a stub types definition for source-map (https://github.com/mozilla/source-map). source-map provides its own type definitions, so you don't need @types/source-map installed!

But I'm not sure as they have last released the version 2 years ago!

**Comment by wooorm** [comment]
I don’t think it’s correct, as you point out, because `source-map` was last published [3 years ago on npm](https://www.npmjs.com/package/source-map).

/cc @silvenon who added it last month in https://github.com/wooorm/xdm/pull/43.

**Comment by silvenon** [comment]
Unfortunately #43 didn't fix my problem, I only thought it did. My problem is somewhere else, but I wasn't able to figure out where.

On npm page for `source-map` you can see the TypeScript icon, which means that it does pack its own type definitions, so @deadcoder0904 is right. Feel free to revert #43.

**Comment by wooorm** [comment]
Hmm okay! Weird. Maybe something is using `resolutions` to use an older `source-map` for you? Otherwise I’d expect that xdm is getting the version it wants (`^0.7.0`, which has the types)

**Comment by wooorm** [comment]
Thanks for reporting @deadcoder0904!

**Comment by deadcoder0904** [comment]
Haha, nice. Can you guys make me understand how it uses types if it was published 3 years ago?

**Comment by wooorm** [comment]
I guess because TS@3 was around already back then!

**Comment by wooorm** [comment]
Released! https://github.com/wooorm/xdm/releases/tag/1.12.0
