### ISSUE TITLE
Cannot use `<!--` for comments with xdm, but Prettier cannot use `{/**/}` for comments

### ISSUE THREAD

**Issue by kentcdodds** [wooorm/xdm#61]
---

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

This one is close, but not quite the same: https://github.com/wooorm/xdm/issues/44

Affected packages and versions: Latest

### Steps to reproduce

Here's a reproduction: https://codesandbox.io/s/xdm-create-react-app-starter-forked-fxd07

It's clear that this is expected (designed?) behavior. However, if my MDX is in a file that I format with prettier, [prettier will convert](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAWQIYCcDWAJhAO5ToAWc2hcuAOlI8APQBU6kAtlwjOmxYBfRowA8APmD0QAKwDOAD07R4sGULEsJIADQgIABxgBLaPOSg8uUgAU8CCymwA3CCcJ6QAI1zYw+HAwAMqG-iZQAObIAGbYADbycPpwXN5whLSEADLYUQCu2JFwAGIQuFzYMKZRyCDY+TAQXhQwXPEA6hQm8PJhYHDBjj0mLj0AnnVg8hb6EUm4MLZ+kZWxCUn6CooAQn4BQcHYvNkRcOuJyXJKwRGR8XAAivkQ8BebIGG4C3VchIpeQy4CIwDoeGAUZAADgADPogRAkh0-IY6gkSNhxrMQABHF7wZZGJz1eQAWigcAyGS8uDgeJMtOWRTWSDil30SS4JneV3kdwez1e5yQMFw+SuMGw3jBhAhyAATPpRdgTPE7gBhCA8bBo+LxLz5JIAFSlTjZHxc4oAklBaLBgmBgcYAIK24IwcYPHlCIRAA) that `{/* comment */}` into `{/_ comment _/}` which ... is not what I want 😅

### Expected behavior

I expect to be able to use code comments without prettier changing it. Is this a prettier or xdm bug?

### Actual behavior

The only code comment option at my disposal is not allowed by prettier.

### My use case

I need to be able to have comments for `prettier-ignore`. In particular, [one of my blog posts](https://github.com/kentcdodds/kentcdodds.com/blob/d7ebfcc7e3e8fb8354f0ca58da8159fccaeeb14d/content/blog/eliminate-an-entire-category-of-bugs-with-a-few-simple-tools/index.mdx#L49-L55) is trying to demonstrate that prettier can help you find bugs so I need that code block to *not* be formatted by prettier to illustrate my point. As of right now, my workaround is to put the comment within the code block, but that makes it visible to the reader which is distracting from the point.

**Comment by ChristianMurphy** [comment]
also related and relevant https://github.com/prettier/prettier/issues/10706

**Comment by wooorm** [comment]
Thanks for the thoughtful repro and info!

Well, it’s not really a bug, but also definitely not nice.
Neither `mdx-js/mdx@next` nor xdm support HTML comments anymore. While it *could* work, it is intentional to not support HTML (including comments), and support more of JS, for a clearer divide that hopefully helps users in the end.

/cc @fisker and @thorn0 from Prettier who recently worked on MDX there: would it be possible [next to HTML-like comments in MDX](https://github.com/prettier/prettier/blob/57f8eec8e65290a0dbb35b4551e152bb4cd48e77/src/language-markdown/mdx.js#L30), to also support JS-like comments (`/{\s*\/\*([^*]|\*(?!=\/))*?\*\/\s*}/`)? (And also support the behavior of `prettier-ignore` comments for them).

Note: I was typing this as I forgot the prettier issue; we can also continue discussing there!

**Comment by kentcdodds** [comment]
> for a clearer divide that hopefully helps users in the end.

Oh, this is actually nice 👍

Yeah, seems like the solution to this use case is in prettier supporting JSX-style comments in MDX.

**Comment by ericclemmons** [comment]
For those on Google that run into this same issue (as I did), I found a trick: **use `{/** ... **/}`** 🙏

**Comment by kentcdodds** [comment]
Nice! Thank you @ericclemmons!

**Comment by fisker** [comment]
> would it be possible next to HTML-like comments in MDX, to also support JS-like comments (/{\s*\/\*([^*]|\*(?!=\/))*?\*\/\s*}/)?

I'm sorry, I'm not familiar with that part, if you think that works, PR welcome.

**Comment by kentcdodds** [comment]
Note: while the `{/** ... **/}` workaround from @ericclemmons *does* work for adding comments, it does not seem to work with `prettier-ignore` so my original use case still won't work :(

**Comment by wooorm** [comment]
I’ve opened a PR with prettier: https://github.com/prettier/prettier/pull/11563.
If anyone is familiar with the Prettier codebase that can help me and others move this along, that’d be appreciated!

**Comment by pomber** [comment]
This now works (Prettier v2.5.0):

~~~md
{/* prettier-ignore */}
```js
console.log("no" 
	+ " " 
	+ "touching")
```
~~~
[Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKBiABACTgG3wnXWAHoAqLABwCc4YYBLOWgWiYHMoJ6sKyAX3QADMQCsAzukhRJEfHAB0RTgApUIHpqwkYAal0gjuqKgNGYEAK5gAFkyidNASlFiQAGhARqzaJLIoACGtLQQAO4ACqEIgSjB+BHBAJ6B3gBGtMFgANYMAMrBALZwADKOcMgAZomScJnZeYXUOY6cyDC01g0gcMUZcAAmQ8NlwU7WwZxwAGK8xcGM7cggwdZWXiB2MMX4AOoO8JKtYHAFcUzMAG5XKatgkukgjvW0MFHZnIs1db1SAA8Cu1FABFawQeC-fD1bytWhvVbFIYArZ0RwwfZMIYwOzIAAcAAY4eF6vtstRVnQ4G9rlVvABHCHwT6+eJrSRsKBwYbDLb0JlMeifaY-JC1GG9erFJidbpSkFwcGQqriv7eGDBDJYnF4pAAJg12SY+HaAGEIMUxX1JABWLbWeoAFS18QlsJA1x6AEkoKNYAUwLQmH4AIJ+gowFKKaH1QSCIA)

Thanks @wooorm !

**Comment by wooorm** [comment]
Yay! [release notes](https://prettier.io/blog/2021/11/25/2.5.0.html) 🎉
