### ISSUE TITLE
esbuild-xdm plugin: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by Ehesp** [wooorm/xdm#68]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

### Steps to reproduce

I'm trying to use [`shiki`](https://shiki.matsu.io/) with a remark plugin using [`remark-shiki`](https://github.com/stefanprobst/remark-shiki).

Whenever I include the plugin, I hit the following error:

```
node_modules/esbuild/lib/main.js:869:27: error: [plugin: esbuild-xdm] Cannot read property 'start' of undefined
    869 │               let result = await callback2({
        ╵                            ^
    at onload (.../node_modules/xdm/lib/integration/esbuild.js:86:32)
...
node_modules/esbuild/lib/main.js:736:22: note: This error came from the "onLoad" callback registered here
    736 │         let promise = setup({
```

I wasn't sure this was an issue with the plugin or not, so I confirmed the same error occurs with a basic plugin:

```js
export default function testPlugin() {
  return async () => {
    const highlighter = await shiki.getHighlighter({
      theme: 'github',
    });
  };
}
```

**Comment by wooorm** [comment]
Can you post the smallest content that produces this error?

**Comment by wooorm** [comment]
The sample plugin also isn't doing anything?

**Comment by Ehesp** [comment]
Ok sorry was being a bit of an idiot.

```diff
- import shiki from 'shiki';
+ import { getHighlighter } from 'shiki';
```

This fixed it, so nothing to do with your library sorry. The only thing I did to find the error was log it [here](https://github.com/wooorm/xdm/blob/main/lib/integration/esbuild.js#L155), which returned `TypeError: Cannot read property 'getHighlighter' of undefined`.

It seems that error has no `location` property, hence the original error.

**Comment by wooorm** [comment]
Might still be something to change here, to throw the actual error instead of hiding it and throwing something else? 🤔 if it's something here, though?

**Comment by wooorm** [comment]
Thanks for the repro. This is, sort of, with `@stefanprobst/remark-shiki`. The swallowed error is:

```
Error: Cannot handle unknown node `raw`
    at Object.unknown (file:///Users/tilde/Projects/oss/example-next-mdx-bundler-shiki/node_modules/hast-util-to-estree/index.js:155:9)
    // ... 
```

`@stefanprobst/remark-shiki` is injecting HTML into the AST. xdm (and the upcoming MDX v2) don’t handle HTML.
You could get around it, [by using `rehype-raw` with these options, in `rehypePlugins`](https://github.com/wooorm/xdm/blob/4bdee4d0ef7bd12f0c52f69d8247abcd5039cb4d/test/core.js#L659).

Having to use `rehype-raw` is documented in the readme of `@stefanprobst/remark-shiki`.
Note that there are several rehype shiki plugins! [`rehype-shiki`](https://github.com/rsclarke/rehype-shiki), seems to build an AST, not strings of HTML. Maybe the other ones work better.

Meanwhile I’ll try and make sure errors aren’t swallowed

/cc @stefanprobst, author of `@stefanprobst/remark-shiki`

**Comment by stefanprobst** [comment]
hi, yep the [example in the docs](https://github.com/stefanprobst/remark-shiki#how-to-use) shows using `rehype-raw`.

as @wooorm mentioned, there are a couple of rehype shiki plugins - i've got [my own one](https://github.com/stefanprobst/rehype-shiki) as well, which i'm successfully using with xdm.
