### ISSUE TITLE
Upgrade micromark deps?

### ISSUE THREAD

**Issue by kentcdodds** [wooorm/xdm#76]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: 1.12.2

### Steps to reproduce

I'm struggling to figure out how to reproduce this issue 😬 I'm experiencing it in https://github.com/kentcdodds/remix-kentcdodds but you'd need a remix license to run that 😅

### Expected behavior

I expect to be able to use the latest version of all packages together without trouble.

### Actual behavior

Basically, when I use the latest version of `remark-gfm` with the latest version of `xdm`, I run into the issue mentioned here: https://github.com/wooorm/xdm/issues/75 and I'm pretty sure it has to do with the fact that xdm is still using (transitively) an old version of remark-parser and micromark:

```
npm ls micromark
kentcdodds.com@1.0.0 /Users/kentcdodds/code/remix-kentcdodds
├─┬ mdx-bundler@5.2.1
│ └─┬ xdm@1.12.2
│   ├─┬ micromark-extension-mdxjs@0.3.0
│   │ ├─┬ micromark-extension-mdx-expression@0.3.2
│   │ │ └── micromark@2.11.4
│   │ ├─┬ micromark-extension-mdx-jsx@0.3.3
│   │ │ └── micromark@2.11.4
│   │ ├─┬ micromark-extension-mdxjs-esm@0.3.1
│   │ │ └── micromark@2.11.4
│   │ └── micromark@2.11.4
│   └─┬ remark-parse@9.0.0
│     └─┬ mdast-util-from-markdown@0.8.5
│       └── micromark@2.11.4
└─┬ remark-parse@10.0.0
  └─┬ mdast-util-from-markdown@1.0.0
    └── micromark@3.0.3
```

The only workaround I've found so far is to downgrade `remark-gfm` to 1.0.0.

**Comment by ChristianMurphy** [comment]
Heya @kentcdodds :wave:  you ran into a spot of trouble.
This is related to unified rolling out new majors of most plugins https://github.com/unifiedjs/unified/issues/121 
These updates are currently making their way through `remark-*` packages. (for example `react-markdown` is also in a similar spot temporarily waiting for updates https://github.com/remarkjs/react-markdown/issues/626 https://github.com/remarkjs/react-markdown/issues/629)
Soon after `remark-*` packages are updated, `xdm` can be updated.


A fix is incoming :rocket: as a temporary workaround hold `remark-*` plugins one major release back from latest.

**Comment by wooorm** [comment]
I’m halve way with `remark-lint`. Which I can probably finish today. So expect xdm/react-markdown end-of-day or tomorrow!

**Comment by wooorm** [comment]
done!

**Comment by kentcdodds** [comment]
Sweet! Thank you so much. It feels *so good* to be able to be on the latest version of every one of my deps :)
