### ISSUE TITLE
Add a migrating from mdx-js/mdx@1 guide

### ISSUE THREAD

**Issue by wooorm** [wooorm/xdm#78]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

### Subject

More and more users are moving. Some stuff like `remark-gfm` not being there should be explained somewhere.

### Problem

There are a few differences, now detailed at the end in a boring list of differences.

### Solution

Migration guide. Either for mdx-js/mdx@1, mdx-js/mdx@2, or both?

### Alternatives

🤷‍♂️

**Comment by ChristianMurphy** [comment]
Probably for MDX 1.
Some questions I could see people having:
* How is content handled different?
    * changes to JSX block handling
    * changes to Markdown/JSX interleaving
    * handling of indented code blocks
    * comments changes
    * GFM and Footnotes now require a plugin
* How to migrate integration with: X?
    * Gatsby
    * Next
    * Storybook
    * Create React App

**Comment by wooorm** [comment]
going to close this as work has resumed on mdx-js/mdx, but I’ll take those good points @ChristianMurphy!
