### ISSUE TITLE
Importing xdm on Next.js results in Webpack fail: reading from "node:assert" is not handled by plugins

### ISSUE THREAD

**Issue by AnthonyKuang** [wooorm/xdm#84]
---

Choosing question instead of issue because I feel this is more related to Next.js than xdm, but wanted to make sure I'm not missing anything obvious.

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

Affected packages and versions: latest, Node.js lts

### Steps to reproduce

Run `npx create-next-app`, [turn on ESM Externals](https://nextjs.org/blog/next-11-1#es-modules-support) in `next.config.js`, then import `xdm` from any file in the `pages` directory.

```jsx
import Head from 'next/head';
import { evaluate } from 'xdm';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
      </Head>
    </div>
  );
}
```

throws error on `npm run dev`:

```bash
error - node:assert
Module build failed: UnhandledSchemeError: Reading from "node:assert" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Could not find files for / in .next/build-manifest.json
Could not find files for / in .next/build-manifest.json
```

A bit confused as to why this is the only package that Next.js doesn't agree with in my dependencies

**Comment by wooorm** [comment]
Hi there!

This might be related to `assert`.
In which case, see https://github.com/micromark/micromark/issues/87. Specifically the last two ideas I laid out in: https://github.com/micromark/micromark/issues/87#issuecomment-908924233.

It might also be related to the `node:` protocol, and that webpack perhaps doesn’t support it yet?

**Comment by with-heart** [comment]
@AnthonyKuang Were you able to add support for `node:`?

**Comment by AnthonyKuang** [comment]
@with-heart No, I wasn't. I ended up downgrading `xdm` to `1.12.2` to support nextjs. The nextjs config [doesn't seem to support it](https://github.com/vercel/next.js/issues/28774) and i'm not good at modifying webpack - in either case it's unrelated to xdm. There is also continuous discussion in https://github.com/micromark/micromark/issues/87 so I'll be on the lookout there

**Comment by with-heart** [comment]
@AnthonyKuang Thank you! Trying to downgrade was going to be my next step, but wanted to check just in case! Will subscribe to the `micromark` issue as well
