### ISSUE TITLE
Using MDXProvider for evaluate, options.useMDXComponents

### ISSUE THREAD

**Issue by AnthonyKuang** [wooorm/xdm#86]
I am having trouble using an `MDXProvider` from `@mdx-js/react` for my MDX output after using `evaluate`. This application is a live runtime editor using `evaluate`. Here is a minimal reproduction:

### `evaluate` - note `useMDXComponents`

```js
// /lib/xdm.js

import { evaluate } from 'xdm';
import { useMDXComponents } from '@mdx-js/react';
import * as runtime from 'react/jsx-runtime.js';

export const evaluateMDX = async (mdx, setMDXOutput) => {
  const { default: Content } = await evaluate(mdx, {
    ...runtime,
    useMDXComponents,
    useDynamicImport: true,
  });

  setMDXOutput(Content);
};
```

### Implementation in client using `<MDXProvider />`

```jsx
// /components/MDXContent.js

import { useState, useMemo } from 'react';
import { evaluateMDX } from '@lib/xdm';
import { MDXProvider } from '@mdx-js/react';
import MDXComponents from '@components/MDXComponents';

export default function MDXContent({ mdx }) {
  const [MDXOutput, setMDXOutput] = useState('');

  useMemo(() => {
    evaluateMDX(mdx, setMDXOutput);
  }, [mdx]);

  return (
    <MDXProvider components={MDXComponents}>
      {MDXOutput}
    </MDXProvider>
  );
}
```

### Output

No error messages, however the `<MDXProvider />` doesn't replace any of the components defined in my `MDXComponents`.

### Versions
- xdm@1.12.2
- next@11.1.2
- @mdx-js/react@1.6.22

### Guesses

I think something really obvious is just flying over my head, or perhaps there is a version incompatibility as I'm on the previous version of `xdm`.

**Comment by wooorm** [comment]
Which bundler are you using? I think maybe 
 useMdxComponents is undefined because it isn't a named export?

**Comment by wooorm** [comment]
Also: no need to use the provider at all here! You can pass the components to Content directly!

**Comment by AnthonyKuang** [comment]
Thank you! Totally didn't cross my mind that Content was a component - I was rendering it as a string in my JSX.

aside: I was today years old when I learned that you can use a function component as a value for `useState`. Although this is probably far from best practice, I'm just glad it all works 😆 

## Working code

### `evaluate`

```js
// /lib/xdm.js

import { evaluate } from 'xdm';
import { useMDXComponents } from '@mdx-js/react';
import * as runtime from 'react/jsx-runtime.js';

export const evaluateMDX = async (mdx, setMDXOutput) => {
  const { default: Content } = await evaluate(mdx, {
    ...runtime,
    useMDXComponents,
    useDynamicImport: true,
  });

  setMDXOutput(() => {
      const returnJSX = () => <Content />;
      return returnJSX;
    });
  };
```

### Implementation in client using `<MDXProvider />`

```jsx
// /components/MDXContent.js

import { useState, useMemo } from 'react';
import { evaluateMDX } from '@lib/xdm';
import { MDXProvider } from '@mdx-js/react';
import MDXComponents from '@components/MDXComponents';

export default function MDXContent({ mdx }) {
  const [MDXOutput, setMDXOutput] = useState(() => {
    const returnJSX = ({ children }) => <>{children}</>;
    return returnJSX;
  );

  useMemo(() => {
    evaluateMDX(mdx, setMDXOutput);
  }, [mdx]);

  return (
    <MDXProvider components={MDXComponents}>
      <MDXOutput />
    </MDXProvider>
  );
}
```
