### ISSUE TITLE
Question: What is the roadmap for XDM and how does it relate to MDX 2?

### ISSUE THREAD

**Issue by ElMassimo** [wooorm/xdm#94]
First of all, thank you for making `xdm`, and the entire `unified` ecosystem! ❤️

I'm using `xdm` to power markdown in [îles](https://iles-docs.netlify.app/) through [`vite-plugin-xdm`](https://github.com/ElMassimo/vite-plugin-xdm).

<hr/>

Reading the [docs for the upcoming **MDX 2**](https://v2.mdxjs.com/docs/what-is-mdx/), I see that it's going to be powered by micromark, and I get the sense that it's going to reuse most of the innovations in **xdm**.

Currently, **xdm** seems to be a platform to explore [new ideas](https://github.com/wooorm/xdm#-lab) and iterate faster than you would be able to in a more established project like **MDX**.

Would you share your plans regarding **xdm** once **MDX 2** is released?

**Comment by wooorm** [comment]
Heya!

I ported xdm back into mdx. They’re virtually identical now. Only differences is that xdm is semver stable whereas mdx is “unstable” (although I don’t expect anything to change for V2).

> Currently, xdm seems to be a platform to explore new ideas and iterate faster than you would be able to in a more established project like MDX.

True. But also a lot of work to maintain many projects. I’m not sure how much more experimentation there needs to be. E.g., the `allowDangerousRemoteMdx` option or so is documented as not adhering to semver, to allow for experimentation.
